export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  REMEDIAL_LOCKED: "REMEDIAL_LOCKED",
  REMEDIAL_EMPTY: "REMEDIAL_EMPTY",
  REMEDIAL_NOT_FOUND: "REMEDIAL_NOT_FOUND"
} as const;
