export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  REMEDIAL_EMPTY_GROUP: "REMEDIAL_EMPTY_GROUP",
  REMEDIAL_LOCKED: "REMEDIAL_LOCKED"
} as const;
